export type ProductCategory = 'men' | 'women' | 'unisex';

export type Product = {
  id: number;
  name: string;
  slug: string;
  category: ProductCategory;
  price: number;
  oldPrice?: number;
  image: string;
  images: string[];
  badge?: string;
  description: string;
  colors: string[];
  sizes: string[];
  fabric: string;
  fit: string;
  sku: string;
  inStock: boolean;
  rating: number;
  reviews: number;
};

export type Category = {
  slug: ProductCategory;
  title: string;
  description: string;
  image: string;
};

export type NavLink = {
  href: string;
  label: string;
};

export const navLinks: NavLink[] = [
  { href: '/', label: 'Home' },
  { href: '/products', label: 'Products' },
  { href: '/categories', label: 'Categories' },
  { href: '/cart', label: 'Cart' },
];

export const categories: Category[] = [
  {
    slug: 'men',
    title: "Men's T-Shirts",
    description: 'Structured fits, refined basics, and easy everyday layers for men.',
    image: '/images/Tshirts/men/m1.png',
  },
  {
    slug: 'women',
    title: "Women's T-Shirts",
    description: 'Soft silhouettes, versatile neutrals, and elevated casual styling for women.',
    image: '/images/Tshirts/women/10.jpg',
  },
  {
    slug: 'unisex',
    title: 'Unisex T-Shirts',
    description: 'Relaxed cuts and versatile essentials designed for everyone.',
    image: '/images/Tshirts/unisex/2.jpg',
  },
];

export const products: Product[] = [
  // MEN
  {
    id: 1,
    name: 'Classic Core Tee',
    slug: 'classic-core-tee',
    category: 'men',
    price: 1990,
    oldPrice: 2600,
    image: '/images/Tshirts/men/m1.png',
    images: ['/images/Tshirts/men/m1.png', '/images/Tshirts/men/12.jpg', '/images/Tshirts/men/13.jpg'],
    badge: 'Best Seller',
    description: 'A clean everyday men\'s T-shirt with a structured fit and smooth premium cotton handfeel. Designed for all-day comfort with a timeless silhouette that pairs with anything.',
    colors: ['Black', 'White', 'Olive'],
    sizes: ['S', 'M', 'L', 'XL'],
    fabric: 'Premium Jersey Cotton',
    fit: 'Regular Fit',
    sku: 'RF-M-001',
    inStock: true,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 2,
    name: 'Minimal Logo Tee',
    slug: 'minimal-logo-tee',
    category: 'men',
    price: 2100,
    oldPrice: 2800,
    image: '/images/Tshirts/men/12.jpg',
    images: ['/images/Tshirts/men/12.jpg', '/images/Tshirts/men/13.jpg', '/images/Tshirts/men/14.jpg'],
    badge: 'Trending',
    description: 'Minimal branding, structured shoulders, and a polished look for daily wear. The subtle logo detailing adds character without overpowering the clean aesthetic.',
    colors: ['Black', 'Stone', 'Navy'],
    sizes: ['M', 'L', 'XL'],
    fabric: 'Premium Jersey',
    fit: 'Relaxed Fit',
    sku: 'RF-M-002',
    inStock: true,
    rating: 4.6,
    reviews: 57,
  },
  {
    id: 3,
    name: 'Urban Street Tee',
    slug: 'urban-street-tee',
    category: 'men',
    price: 1850,
    oldPrice: 2400,
    image: '/images/Tshirts/men/13.jpg',
    images: ['/images/Tshirts/men/13.jpg', '/images/Tshirts/men/14.jpg', '/images/Tshirts/men/15.jpg'],
    badge: 'New',
    description: 'Inspired by city streets and modern culture. This tee features a slightly dropped shoulder and relaxed body for an effortlessly cool look.',
    colors: ['Black', 'Charcoal', 'White'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    fabric: 'Cotton Blend',
    fit: 'Oversized Fit',
    sku: 'RF-M-003',
    inStock: true,
    rating: 4.7,
    reviews: 83,
  },
  {
    id: 4,
    name: 'Essential Everyday Tee',
    slug: 'essential-everyday-tee',
    category: 'men',
    price: 1750,
    image: '/images/Tshirts/men/14.jpg',
    images: ['/images/Tshirts/men/14.jpg', '/images/Tshirts/men/15.jpg', '/images/Tshirts/men/16.jpg'],
    description: 'Your go-to daily T-shirt. Made from soft, breathable cotton that keeps you comfortable from morning to night. A wardrobe staple in every color.',
    colors: ['White', 'Grey', 'Beige'],
    sizes: ['S', 'M', 'L', 'XL'],
    fabric: '180 GSM Cotton',
    fit: 'Classic Fit',
    sku: 'RF-M-004',
    inStock: true,
    rating: 4.5,
    reviews: 42,
  },
  {
    id: 5,
    name: 'Heavyweight Drop Shoulder',
    slug: 'heavyweight-drop-shoulder',
    category: 'men',
    price: 2490,
    oldPrice: 3200,
    image: '/images/Tshirts/men/15.jpg',
    images: ['/images/Tshirts/men/15.jpg', '/images/Tshirts/men/16.jpg', '/images/Tshirts/men/17.jpg'],
    badge: 'Editor Pick',
    description: 'Made from 240 GSM heavyweight cotton for a premium, structured feel. The drop shoulder cut gives it a modern streetwear edge that stands out.',
    colors: ['Black', 'Cream', 'Olive'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    fabric: '240 GSM Heavy Cotton',
    fit: 'Drop Shoulder Oversized',
    sku: 'RF-M-005',
    inStock: true,
    rating: 4.9,
    reviews: 198,
  },
  {
    id: 6,
    name: 'Clean Crew Tee',
    slug: 'clean-crew-tee',
    category: 'men',
    price: 1650,
    image: '/images/Tshirts/men/16.jpg',
    images: ['/images/Tshirts/men/16.jpg', '/images/Tshirts/men/17.jpg', '/images/Tshirts/men/18.jpg'],
    description: 'A perfectly clean crew neck tee with a refined cut and soft handfeel. Versatile enough for casual outings or smart casual styling.',
    colors: ['White', 'Black', 'Light Blue'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    fabric: 'Soft Cotton Jersey',
    fit: 'Slim Fit',
    sku: 'RF-M-006',
    inStock: true,
    rating: 4.4,
    reviews: 35,
  },
  {
    id: 7,
    name: 'Reflect Signature Tee',
    slug: 'reflect-signature-tee',
    category: 'men',
    price: 2250,
    oldPrice: 2900,
    image: '/images/Tshirts/men/17.jpg',
    images: ['/images/Tshirts/men/17.jpg', '/images/Tshirts/men/18.jpg', '/images/Tshirts/men/19.jpg'],
    badge: 'Popular',
    description: 'The signature piece from Reflect Fashion. Premium ring-spun cotton with a perfectly proportioned fit that sits well on all body types.',
    colors: ['Black', 'White', 'Burgundy'],
    sizes: ['S', 'M', 'L', 'XL'],
    fabric: 'Ring-Spun Cotton',
    fit: 'Regular Fit',
    sku: 'RF-M-007',
    inStock: true,
    rating: 4.8,
    reviews: 156,
  },
  {
    id: 8,
    name: 'Coastal Breeze Tee',
    slug: 'coastal-breeze-tee',
    category: 'men',
    price: 1900,
    image: '/images/Tshirts/men/18.jpg',
    images: ['/images/Tshirts/men/18.jpg', '/images/Tshirts/men/19.jpg', '/images/Tshirts/men/20.jpg'],
    description: 'Lightweight and breathable, ideal for warm weather. The airy cotton weave keeps you cool and fresh all day.',
    colors: ['Sky Blue', 'White', 'Sand'],
    sizes: ['S', 'M', 'L', 'XL'],
    fabric: 'Lightweight Cotton',
    fit: 'Relaxed Fit',
    sku: 'RF-M-008',
    inStock: true,
    rating: 4.6,
    reviews: 61,
  },

  // WOMEN
  {
    id: 9,
    name: 'Soft Street Tee',
    slug: 'soft-street-tee',
    category: 'women',
    price: 1850,
    oldPrice: 2400,
    image: '/images/Tshirts/women/11.jpg',
    images: ['/images/Tshirts/women/11.jpg', '/images/Tshirts/women/1.jpg', '/images/Tshirts/women/2.jpg'],
    badge: 'New',
    description: 'A soft-touch women\'s T-shirt with a balanced shape for casual and smart styling. The premium cotton blend ensures comfort throughout the day.',
    colors: ['Cream', 'Black', 'Rose'],
    sizes: ['XS', 'S', 'M', 'L'],
    fabric: 'Cotton Blend',
    fit: 'Slim Relaxed Fit',
    sku: 'RF-W-001',
    inStock: true,
    rating: 4.7,
    reviews: 89,
  },
  {
    id: 10,
    name: 'Studio Basic Tee',
    slug: 'studio-basic-tee',
    category: 'women',
    price: 1650,
    oldPrice: 2100,
    image: '/images/Tshirts/women/1.jpg',
    images: ['/images/Tshirts/women/1.jpg', '/images/Tshirts/women/2.jpg', '/images/Tshirts/women/3.jpg'],
    badge: 'Sale',
    description: 'A lightweight studio-inspired T-shirt with an elegant neckline and smooth drape. Perfect for yoga, brunch, or everyday casual wear.',
    colors: ['White', 'Sand', 'Blush'],
    sizes: ['XS', 'S', 'M'],
    fabric: 'Soft Cotton',
    fit: 'Classic Fit',
    sku: 'RF-W-002',
    inStock: true,
    rating: 4.5,
    reviews: 33,
  },
  {
    id: 11,
    name: 'Feminine Crop Tee',
    slug: 'feminine-crop-tee',
    category: 'women',
    price: 1750,
    image: '/images/Tshirts/women/2.jpg',
    images: ['/images/Tshirts/women/2.jpg', '/images/Tshirts/women/3.jpg', '/images/Tshirts/women/4.jpg'],
    badge: 'Popular',
    description: 'A slightly cropped silhouette with a relaxed fit that pairs effortlessly with high-waisted bottoms. Casual, feminine, and endlessly stylish.',
    colors: ['White', 'Black', 'Lavender'],
    sizes: ['XS', 'S', 'M', 'L'],
    fabric: '160 GSM Cotton',
    fit: 'Cropped Relaxed',
    sku: 'RF-W-003',
    inStock: true,
    rating: 4.8,
    reviews: 112,
  },
  {
    id: 12,
    name: 'Minimalist V-Neck',
    slug: 'minimalist-v-neck',
    category: 'women',
    price: 1900,
    oldPrice: 2500,
    image: '/images/Tshirts/women/3.jpg',
    images: ['/images/Tshirts/women/3.jpg', '/images/Tshirts/women/4.jpg', '/images/Tshirts/women/5.jpg'],
    badge: 'Best Seller',
    description: 'A clean V-neck silhouette in premium cotton. Elegant and effortless — the kind of T-shirt you\'ll reach for again and again.',
    colors: ['Black', 'White', 'Terracotta'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    fabric: 'Premium Combed Cotton',
    fit: 'Fitted',
    sku: 'RF-W-004',
    inStock: true,
    rating: 4.9,
    reviews: 204,
  },
  {
    id: 13,
    name: 'Relaxed Oversized Tee',
    slug: 'relaxed-oversized-tee',
    category: 'women',
    price: 2100,
    image: '/images/Tshirts/women/4.jpg',
    images: ['/images/Tshirts/women/4.jpg', '/images/Tshirts/women/5.jpg', '/images/Tshirts/women/6.jpg'],
    description: 'The oversized silhouette you\'ve been looking for. Soft, roomy, and endlessly cozy — wear it as a dress or over your favorite leggings.',
    colors: ['Grey', 'White', 'Sage'],
    sizes: ['S', 'M', 'L'],
    fabric: 'Heavy Cotton Jersey',
    fit: 'Oversized',
    sku: 'RF-W-005',
    inStock: true,
    rating: 4.7,
    reviews: 78,
  },
  {
    id: 14,
    name: 'Pastel Everyday Tee',
    slug: 'pastel-everyday-tee',
    category: 'women',
    price: 1590,
    image: '/images/Tshirts/women/5.jpg',
    images: ['/images/Tshirts/women/5.jpg', '/images/Tshirts/women/6.jpg', '/images/Tshirts/women/7.jpg'],
    badge: 'New',
    description: 'Soft pastel colors and a gentle silhouette for a laid-back, feminine look. Made from breathable cotton that feels like a second skin.',
    colors: ['Powder Pink', 'Mint', 'Baby Blue'],
    sizes: ['XS', 'S', 'M', 'L'],
    fabric: 'Breathable Cotton',
    fit: 'Regular Fit',
    sku: 'RF-W-006',
    inStock: true,
    rating: 4.6,
    reviews: 45,
  },

  // UNISEX
  {
    id: 15,
    name: 'Everyday Unisex Tee',
    slug: 'everyday-unisex-tee',
    category: 'unisex',
    price: 1800,
    oldPrice: 2350,
    image: '/images/Tshirts/unisex/8.jpg',
    images: ['/images/Tshirts/unisex/8.jpg', '/images/Tshirts/unisex/1.jpg', '/images/Tshirts/unisex/2.jpg'],
    badge: 'Popular',
    description: 'A versatile unisex T-shirt designed for comfort, layering, and easy styling. The relaxed silhouette looks great on all body types.',
    colors: ['Grey', 'White', 'Navy', 'Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    fabric: 'Heavy Cotton',
    fit: 'Oversized Fit',
    sku: 'RF-U-001',
    inStock: true,
    rating: 4.9,
    reviews: 211,
  },
  {
    id: 16,
    name: 'Oversized Daily Tee',
    slug: 'oversized-daily-tee',
    category: 'unisex',
    price: 2200,
    oldPrice: 2900,
    image: '/images/Tshirts/unisex/1.jpg',
    images: ['/images/Tshirts/unisex/1.jpg', '/images/Tshirts/unisex/2.jpg', '/images/Tshirts/unisex/3.jpg'],
    badge: 'Editor Pick',
    description: 'An oversized drop-shoulder T-shirt that works for modern streetwear styling. The boxy cut and premium fabric make it a statement piece.',
    colors: ['Charcoal', 'Milk', 'Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    fabric: '240 GSM Cotton',
    fit: 'Oversized Fit',
    sku: 'RF-U-002',
    inStock: true,
    rating: 4.8,
    reviews: 73,
  },
  {
    id: 17,
    name: 'Neutral Tone Tee',
    slug: 'neutral-tone-tee',
    category: 'unisex',
    price: 1950,
    image: '/images/Tshirts/unisex/2.jpg',
    images: ['/images/Tshirts/unisex/2.jpg', '/images/Tshirts/unisex/3.jpg', '/images/Tshirts/unisex/4.jpg'],
    badge: 'Trending',
    description: 'Earth-tone palette meets minimal design. This tee is for those who appreciate understated style and quality that lasts.',
    colors: ['Ecru', 'Tan', 'Slate'],
    sizes: ['S', 'M', 'L', 'XL'],
    fabric: 'Washed Cotton',
    fit: 'Regular Fit',
    sku: 'RF-U-003',
    inStock: true,
    rating: 4.7,
    reviews: 94,
  },
  {
    id: 18,
    name: 'Boxy Street Tee',
    slug: 'boxy-street-tee',
    category: 'unisex',
    price: 2050,
    oldPrice: 2700,
    image: '/images/Tshirts/unisex/3.jpg',
    images: ['/images/Tshirts/unisex/3.jpg', '/images/Tshirts/unisex/4.jpg', '/images/Tshirts/unisex/5.jpg'],
    badge: 'New',
    description: 'A boxy, structured silhouette that channels modern streetwear. Oversized proportions and premium fabric make this an instant favourite.',
    colors: ['Black', 'White', 'Forest Green'],
    sizes: ['S', 'M', 'L', 'XL'],
    fabric: 'Cotton Fleece',
    fit: 'Boxy Fit',
    sku: 'RF-U-004',
    inStock: true,
    rating: 4.8,
    reviews: 67,
  },
  {
    id: 19,
    name: 'Chill Vibes Tee',
    slug: 'chill-vibes-tee',
    category: 'unisex',
    price: 1700,
    image: '/images/Tshirts/unisex/4.jpg',
    images: ['/images/Tshirts/unisex/4.jpg', '/images/Tshirts/unisex/5.jpg', '/images/Tshirts/unisex/6.jpg'],
    description: 'Made for those slow, laid-back days. Super soft fabric with a generous fit — the T-shirt that becomes your weekend uniform.',
    colors: ['Sky', 'White', 'Peach'],
    sizes: ['S', 'M', 'L', 'XL'],
    fabric: 'Soft Jersey',
    fit: 'Relaxed Fit',
    sku: 'RF-U-005',
    inStock: true,
    rating: 4.6,
    reviews: 51,
  },
  {
    id: 20,
    name: 'Heritage Washed Tee',
    slug: 'heritage-washed-tee',
    category: 'unisex',
    price: 2350,
    oldPrice: 3000,
    image: '/images/Tshirts/unisex/5.jpg',
    images: ['/images/Tshirts/unisex/5.jpg', '/images/Tshirts/unisex/6.jpg', '/images/Tshirts/unisex/7.jpg'],
    badge: 'Best Seller',
    description: 'Vintage-washed cotton with a perfectly broken-in feel from day one. This is the tee that looks better the more you wear it.',
    colors: ['Vintage Black', 'Washed Navy', 'Faded Green'],
    sizes: ['S', 'M', 'L', 'XL'],
    fabric: 'Washed 220 GSM Cotton',
    fit: 'Relaxed Fit',
    sku: 'RF-U-006',
    inStock: true,
    rating: 4.9,
    reviews: 183,
  },
];

export const featuredProducts = products.filter(p => p.badge === 'Best Seller' || p.badge === 'Editor Pick').slice(0, 4);
export const trendingProducts = products.slice(0, 8);

export const services = [
  { icon: '🚚', title: 'Free Delivery', description: 'Free shipping on orders over Rs. 3,000 island-wide.' },
  { icon: '💵', title: 'Cash on Delivery', description: 'Pay when your order arrives. No card needed.' },
  { icon: '↩️', title: 'Easy Returns', description: '7-day hassle-free return policy on all items.' },
  { icon: '✨', title: 'Premium Quality', description: 'Every tee is crafted from premium cotton for lasting comfort.' },
];